model_name: vgg16
pretrained: True
hidden_size: 4096
out_features: 10  
classifier:
  - requires_grad: True
  - requires_grad: False
  - requires_grad: False
  - requires_grad: True
  - requires_grad: False
  - requires_grad: False
  - last_layer:
      type: linear
      in_features: 4096
      out_features: 10  # Change this to the desired number of output features
      bias: true
